#!/usr/bin/env sh

# From Gerrit Code Review 3.1.3, with some modifications

if test "$#" != 1; then
  echo "$0 requires an argument."
  exit 1
fi
if test ! -f "$1"; then
  echo "file does not exist: $1"
  exit 1
fi
# Create a change id only if requested
if test ! "true" = "$(git config --bool --get gerrit.createChangeId)"; then
  exit 0
fi
# $RANDOM will be undefined if not using bash, so don't use set -u
random=$( (
  whoami
  hostname
  date
  cat "$1"
) | git hash-object --stdin)
dest="$1.tmp.${random}"
trap 'rm -f "${dest}"' EXIT
if ! git stripspace --strip-comments <"$1" >"${dest}"; then
  echo "cannot strip comments from $1"
  exit 1
fi
if test ! -s "${dest}"; then
  echo "file is empty: $1"
  exit 1
fi
# Avoid the --in-place option which only appeared in Git 2.8
# Avoid the --if-exists option which only appeared in Git 2.15
if ! git -c trailer.ifexists=doNothing interpret-trailers \
  --trailer "Change-Id: I${random}" <"$1" >"${dest}"; then
  echo "cannot insert change-id line in $1"
  exit 1
fi
if ! mv "${dest}" "$1"; then
  echo "cannot mv ${dest} to $1"
  exit 1
fi
