#!/usr/bin/env sh

set -e

# We don't have the source_file_if_available function yet
# shellcheck source=/dev/null
FUNCTIONS_FILE_PATH="${HOME}"/.shells/.all/functions.sh && test -f "$FUNCTIONS_FILE_PATH" && . "$FUNCTIONS_FILE_PATH"

while true; do
  echo "Lint the code base? (y/n) "
  read -r yn </dev/tty
  case $yn in
  [Yy]*)
    echo "Linting files..."
    if command -v super_linter; then
      super_linter
    else
      echo "WARNING: Docker daemon is not available. Linting cannot run."
    fi
    ;;
  [Nn]*)
    exit 0
    ;;
  *) echo "Please answer yes or no." ;;
  esac
done

set +e
