name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Super-Linter
        uses: docker://ghcr.io/github/super-linter:v3.13.5
        env:
          ERROR_ON_MISSING_EXEC_BIT: true
          VALIDATE_ALL_CODEBASE: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  setup_ubuntu:
    needs:
      - lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections \
          && apt-get -q update \
          && apt-get -qy install git sudo \
          && ./bin/setup-dotfiles.sh debian \
          && make
