name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-18.04
    steps:
      # Check-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2.3.4

      - name: Super-Linter
        uses: ghcr.io/github/super-linter:v3.13.5
        env:
          ERROR_ON_MISSING_EXEC_BIT: true
          VALIDATE_ALL_CODEBASE: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
