---
name: CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Super-Linter
        uses: super-linter/super-linter@v6.7.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: .
          VALIDATE_ALL_CODEBASE: true

  setup_unix_like:
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotfiles (${{ matrix.os }})
        run: |
          ./setup.sh
    strategy:
      matrix:
        os:
          - macos-12
          - ubuntu-24.04

  setup_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotfiles (Windows)
        run: |
          powershell -executionpolicy bypass ".\setup-windows.ps1"
...
