name: CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Super-Linter
        uses: github/super-linter@v4.2.1
        env:
          ERROR_ON_MISSING_EXEC_BIT: true
          VALIDATE_ALL_CODEBASE: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  setup_ubuntu:
    needs:
      - lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      # Workarounds for https://github.com/actions/virtual-environments/issues/1605
      - run: sudo apt-get purge grub\*
      - name: Setup dotfiles (Ubuntu)
        run: |
          ./bin/setup-dotfiles.sh debian
      - name: Symlink dotfiles
        run: |
          make
  # Disabling this for now because macos is in private beta
  # setup_macos:
  #   needs:
  #     - lint
  #   runs-on: macos-10.5
  #   steps:
  #     - uses: actions/checkout@v2.3.4
  #     - name: Setup dotfiles (macOS)
  #       run: |
  #         ./bin/setup-dotfiles.sh macos
  #     - name: Symlink dotfiles
  #       run: |
  #         make
  setup_windows:
    needs:
      - lint
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Setup dotfiles (Windows)
        run: |
          powershell -executionpolicy bypass ".\bin\install-windows.ps1"
